version: '3'

services:
  node:
    container_name: node
    image: lucasalvess97/node-nginx
    build:
      context: ./app
    networks:
      - node-network
    tty: true
    ports:
      - 3000:3000
    depends_on: 
      db:
        condition: service_healthy

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10

networks:
  node-network:
    driver: bridge